name: @{package.name}
version: @{application.version}
summary: @{package.synopsis}
description: @{package.description}

confinement: strict
grade: stable

architectures: [amd64]

apps:
  filebot:
    command: desktop-launch $SNAP/bin/filebot.sh
    plugs:
      - desktop
      - desktop-legacy
      - x11
      - gsettings
      - dbus
      - home
      - removable-media
      - network
      - network-bind

parts:
  filebot:
    plugin: dump
    source: base
    build-packages:
      - ca-certificates
      - ca-certificates-java
      - openjdk-8-jdk
    stage-packages:
      - openjdk-8-jre
      - openjfx
      - libmediainfo0v5
      - libchromaprint-tools
      - p7zip-full
      - p7zip-rar
      - xdg-utils
      - curl
      - gtk2-engines-murrine
      - libcanberra-gtk-module
      - hicolor-icon-theme
    after:
      - desktop-gtk2
