name: @{package.name}
version: @{application.version}
summary: @{package.synopsis}
description: @{package.description}

confinement: classic
grade: stable

architectures: [amd64]

apps:
  filebot:
    command: bin/filebot.sh

parts:
  filebot:
    plugin: dump
    source: root
