name: @{package.name}
version: @{application.version}
summary: @{package.synopsis}
description: @{package.description}

confinement: classic
grade: stable

architectures: [amd64]

apps:
  filebot:
    command: desktop-launch $SNAP/filebot.sh
    plugs: [unity7, opengl, x11, home, removable-media, network, network-bind, pulseaudio, gsettings]

parts:
  filebot:
    after: [desktop-gtk2]
    plugin: dump
    source: filebot
    stage-packages: [libc6, libmediainfo0v5, libchromaprint-tools, curl]
