name: @{package.name}
version: @{application.version}
summary: @{package.synopsis}
description: @{package.description}

confinement: strict
grade: stable

architectures: [amd64]
base: core18

apps:
  filebot:
    command: desktop-launch $SNAP/bin/filebot.sh
    plugs:
      - desktop
      - desktop-legacy
      - unity7
      - x11
      - opengl
      - gsettings
      - home
      - removable-media
      - network
      - network-bind

environment:
  GTK_PATH: $SNAP/usr/lib/x86_64-linux-gnu/gtk-2.0
  GTK_DATA_PREFIX: $SNAP/usr
  XDG_DATA_DIRS: $SNAP/usr/share:$XDG_DATA_DIRS

parts:
  filebot:
    plugin: dump
    source: base
    build-packages:
      - ca-certificates
      - ca-certificates-java
      - openjdk-8-jdk
    stage-packages:
      - openjdk-8-jre
      - openjfx
      - mediainfo
      - libchromaprint-tools
      - p7zip-full
      - p7zip-rar
      - xdg-utils
      - curl
      - libgnome-2-0
      - libgnomevfs2-0
      - gtk2-engines-murrine
      - libcanberra-gtk-module
      - hicolor-icon-theme
    after:
      - desktop-gtk2
