name: @{package.name}
version: @{application.version}
summary: @{package.synopsis}
description: @{package.description}

confinement: strict
grade: stable

architectures: [amd64]

apps:
  filebot:
    command: desktop-launch $SNAP/bin/filebot.sh
    plugs: [desktop, desktop-legacy, wayland, unity7, x11, gsettings, dbus, home, removable-media, network, network-bind]

plugs:
  gtk-3-themes:
    interface: content
    target: $SNAP/share/themes
    default-provider: gtk-common-themes:gtk-3-themes
  icon-themes:
    interface: content
    target: $SNAP/share/icons
    default-provider: gtk-common-themes:icon-themes
  sound-themes:
    interface: content
    target: $SNAP/share/sounds
    default-provider: gtk-common-themes:sounds-themes

environment:
  XDG_DATA_DIRS: $SNAP/share:$XDG_DATA_DIRS

parts:
  filebot:
    plugin: dump
    source: base
    stage-packages: [openjdk-11-jre, openjfx, libmediainfo0v5, libchromaprint-tools, p7zip-full, p7zip-rar, xdg-utils, curl]
    after: [desktop-gtk3]
